name: test

permissions: {}

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"
          install-go: false

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build ./...

      - name: Go Test
        run: go test -v -count=1 -race -shuffle=on ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...
